FROM openjdk:17-jdk-slim

WORKDIR /app

COPY target/wisdom-0.0.1-SNAPSHOT.jar app.jar

COPY .env .env

ENV SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
ENV SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
ENV SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
